name: build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          bash ./build.sh

      - name: Upload final kernel zip
        uses: actions/upload-artifact@v4
        with:
          name: final-kernel-zip
          path: out/final/*.zip
